apiVersion: v1
kind: Secret
metadata:
  name: vitalsync-db-secret
type: Opaque
data:
  # Les valeurs sont encodees en base64 (echo -n "valeur" | base64)
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
